<?php
/** @var \Zend\Form\Form $registrationForm */
$registrationForm = $this->form;
$registrationForm->prepare();
echo $this->form()->openTag($registrationForm);

?>
<div class="row">
    <div class="col-md-10 main">
        <div class="login">
            <?php //\Zend\Debug\Debug::dump($this->identity()); ?>
            <h1>
                <img src="/application/images/logo.png" alt="HacMan Logo" width="125" height="125"/> Membership System
                <?php
                $button = $this->form->get('submit');
                $button->setAttribute('class', 'btn btn-primary btn-lg btn-login');
                echo $this->formSubmit($button); ?>
            </h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 column">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Login Details
                </h3>
            </div>
            <div class="panel-body">
                <p>These are the details for logging into this site</p>
                <?php
                $details = [
                    'samAccountName',
                    'email',
                    'password',
                    'passwordCheck',
                ];

                foreach ($details as $id) {
                    echo $this->formRow($form->get($id), null, false, 'partials/formElement');
                }

                ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 column">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Your Details
                </h3>
            </div>
            <div class="panel-body">
                <p>Details about you</p>
                <?php
                $details = [
                    'phone',
                    'nickname',
                ];

                echo $this->formRow($form->get('phone'), null, false, 'partials/formElement'); ?>

                <p>Your Nickname - This will be used for display purposes</p>
                <?php echo $this->formRow($form->get('nickname'), null, false, 'partials/formElement'); ?>

                <p>Your Contact Address</p>
                <?php $element = $registrationForm->get('address');
                $element->setAttribute('rows', 5);
                echo $this->formRow($element, null, false); ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 column">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Emergency Details
                </h3>
            </div>
            <div class="panel-body">
                <p>Please tell us who we should contact in case of emergency</p>

                <?php
                $element = $registrationForm->get('emergency_details');
                $element->setAttribute('rows', 5);
                echo $this->formRow($element, null, false); ?>
            </div>
        </div>
    </div>
    <div class="col-md-6 column">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Medical Information
                </h3>
            </div>
            <div class="panel-body">
                <p>Please tell us about any allergies and medical conditions we need to be aware of</p>
                <?php
                $element = $registrationForm->get('medical_information');
                $element->setAttribute('rows', 5);
                echo $this->formRow($element); ?>
            </div>
        </div>
    </div>
</div>

<?php

echo $this->form()->closeTag();
?>

