<div class="row">
    <div class="col-md-12 main">
        <div class="login">
            <?php //\Zend\Debug\Debug::dump($this->identity()); ?>

            <img src="/application/images/logo.png" alt="HacMan Logo"/>

            <h1>Membership System</h1>
        </div>
    </div>
</div>
<div class="row">
    <?php
    $registrationForm = $this->form;
    $registrationForm->prepare();
    echo $this->form()->openTag($registrationForm); ?>

    <div class="col-md-4 column">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Login Details
                </h3>
            </div>
            <div class="panel-body">
                <p>These are the details for logging into this site</p>
                <?php
                $details = [
                    'username',
                    'email',
                    'password',
                    'passwordCheck',
                ];

                foreach($details as $id):
                    $element = $registrationForm->get($id);
                    $element->setAttribute('id', $id);
                    $element->setAttribute('class', 'form-control');
                    $element->setLabelAttributes(['class' => 'input-group-addon']);
                    ?>

                    <div class="input-group input-group-sm"><?php echo $this->formRow($element); ?></div>
                    <br/>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <div class="col-md-6 column">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Your Details
                </h3>
            </div>
            <div class="panel-body">
                <p>Details about you</p>
                <?php
                $details = [
                    'phone',
                    'address_line1',
                    'address_line2',
                    'address_town',
                    'address_city',
                    'address_county',
                    'address_postcode',
                ];

                foreach($details as $id):
                    $element = $registrationForm->get($id);
                    $element->setAttribute('id', $id);
                    $element->setAttribute('class', 'form-control');
                    $element->setLabelAttributes(['class' => 'input-group-addon']);
                ?>

                <div class="input-group input-group-sm"><?php echo $this->formRow($element); ?></div>
                <br/>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    </div>
<div class="row">
    <div class="col-md-12 column">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                   Emergency Details
                </h3>
            </div>
            <div class="panel-body">
                <p>Who to contact and what we should be aware of</p>
                <?php
                $details = [
                    'emergency_details',
                    'medical_information',
                ];

                foreach($details as $id):
                ?>

                <div class="input-group"><?php echo $this->formRow($registrationForm->get($id)->setAttribute('id', $id)); ?></div>
                <br/>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 column">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">
                    Emergency Details
                </h3>
            </div>
            <div class="panel-body">
                <p>Who to contact and what we should be aware of</p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-11 column">&nbsp;</div>
    <div class="col-md-1">
        <?php echo $this->formSubmit($this->form->get('submit')->setAttribute('value', 'Register')); ?>
    </div>
</div>
<?php

echo $this->form()->closeTag();
?>

