<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headTitle(); ?>

    <?php echo $this->headLink(); ?>

    <?php echo $this->headScript(); ?>
</head>
<body class="auth">

<div class="container-fluid">

        <?php echo $this->content; ?>

</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<?php echo $this->placeHolder('footerScripts'); ?>

</body>
</html>
