<?php
/** @var \Zend\Form\Form $form */
$form = $this->migrationForm;
$form->prepare();
?>
<div class="login migrate">

    <img src="/application/images/logo.png" alt="HacMan Logo" />
    <h1>Membership System</h1>
    <p>Your login has been found as part of our old membership database and as such now requires a new password to be set.</p>
    <p>Please enter a new password using the form below</p>
    <?php
    /** @var \Zend\Form\Element\Text $usernameElement */
    $passwordElement = $form->get('password');
    /** @var \Zend\Form\Element\Password $passwordElement */
    $passwordCheckElement = $form->get('passwordCheck');

    /** @var \Zend\Form\View\Helper\FormElementErrors $elementErrors */
    $elementErrors =$this->formElementErrors();
    $message = $elementErrors
        ->setMessageOpenFormat('<li class="elementError">')
        ->setMessageCloseString('</li>')
        ->setMessageSeparatorString('</li><li class="elementError">')
        ->render($form);

    if ($this->flashMessenger()->hasMessages() || !empty($message)) {
        ?>
        <ul class="alert alert-danger">
            <?php
            if (!empty($message)):
                echo $message;
            endif;

            foreach ($this->flashMessenger()->getMessages() as $message) : ?>
                <li class="loginError"><?= $message; ?></li>
            <?php endforeach; ?>
        </ul>
        <?php
        $this->flashMessenger()->clearMessages();
    }
    ?>

    <form method="post">
        <div class="form-group">
            <label for="login_password" class="hide">Email</label>
            <?=$this->formPassword($passwordElement->setAttributes([
                'id' => 'login__password',
                'placeholder' => 'Password',
                'class' => 'form-control'
            ])); ?>
        </div>
        <div class="form-group">
            <label for="login__passwordCheck" class="hide">Password</label>
            <?=$this->formPassword($passwordCheckElement->setAttributes([
                'id' => 'login__passwordCheck',
                'placeholder' => 'Password Again',
                'class' => 'form-control'
            ])); ?>
        </div>
        <button type="submit" class="btn btn-primary" name="submit">Log in</button>
    </form>
</div>